# Generated by Django 5.0.4 on 2024-04-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.TextField(verbose_name='Название игры')),
                ('game_description', models.TextField(blank=True, null=True, verbose_name='Описание игры')),
                ('task_text', models.TextField(blank=True, null=True, verbose_name='Текст задания')),
                ('task_img', models.ImageField(blank=True, null=True, upload_to='games', verbose_name='Картинка к игре')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_created=True, verbose_name='Дата и время создания записи')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('score', models.IntegerField(verbose_name='score')),
            ],
            options={
                'verbose_name': 'GameResult',
                'verbose_name_plural': 'GameResults',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_question_in_game', models.BooleanField(default=False, verbose_name='Является первым вопросом в игре')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_number', models.CharField(max_length=20, verbose_name='Порядковый номер')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions', verbose_name='Картинка к вопросу')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('score', models.IntegerField(verbose_name='Баллы за ответ')),
                ('is_game_over', models.BooleanField(default=False, verbose_name='Игра проиграна')),
                ('game_over_description', models.TextField(blank=True, null=True, verbose_name='Описание причины проигрыша')),
                ('is_last_answer_in_game', models.BooleanField(default=False, verbose_name='Является последним в игре')),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='game.question', verbose_name='Следующий вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('id',),
            },
        ),
    ]
