# Generated by Django 5.0.4 on 2024-04-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',), 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',), 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ('id',), 'verbose_name': 'Результат игры', 'verbose_name_plural': 'Результаты игры'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.character', verbose_name='Персонаж'),
        ),
    ]
