# Generated by Django 5.0.4 on 2024-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_character_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/characters', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='game',
            name='task_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/games', verbose_name='Картинка к игре'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/questions', verbose_name='Картинка к вопросу'),
        ),
    ]
