# Generated by Django 5.0.4 on 2024-04-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_character_character_img_alter_game_task_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.game', verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question', verbose_name='Вопрос'),
        ),
    ]
