# Generated by Django 5.0.4 on 2024-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_answer_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_img_description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст к картинке'),
        ),
    ]
