# Generated by Django 5.0.4 on 2024-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_question_question_img_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
