# Generated by Django 5.0.4 on 2024-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='character',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
