# Generated by Django 5.0.4 on 2024-05-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_question_character_delete_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
    ]
