# Generated by Django 5.0.4 on 2024-05-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
