# Generated by Django 5.0.4 on 2024-05-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_question_question_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_last_answer_in_game',
        ),
    ]
